Client/Ponto/Controllers/CargoController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Ponto.Models;
using Ponto.Views.Cadastro.Cargo;
using Ponto.Views.Cadastro.Departamento;
using System.Text;

namespace Ponto.Controllers
{
    public class CargoController : Controller
    {
        private static readonly HttpClient client = new HttpClient();

        private readonly Routes _routes;
        public CargoController(Routes routes)
        {
            _routes = routes;
        }

        [HttpGet]
        [Route("api/Cargo/Cargo/Cargo")]
        public async Task<IActionResult> Cargo(string username)
        {
            if (User.Identity.IsAuthenticated)
            {
                var response = await client.GetAsync(_routes.rota_cargo);

                var result = await response.Content.ReadAsStringAsync();
                var Cargos = JsonConvert.DeserializeObject<List<Cargo>>(result);

                foreach (var cargo in Cargos)
                {
                    int idDepartamento = cargo.Id_Departamento;
                    string dsDepartamento = "";

                    var rotaDepartamento = _routes.rota_departamento + idDepartamento.ToString();
                    var response2 = await client.GetAsync(rotaDepartamento);
                    var result2 = await response2.Content.ReadAsStringAsync();
                    var apiResponse = JsonConvert.DeserializeObject<ApiResponseListaDepto>(result2);
                    if (apiResponse.Departamentos != null && apiResponse.Departamentos.Count > 0)
                    {
                        var departamento = apiResponse.Departamentos[0]; 
                        cargo.Departamento = departamento.Descricao;
                    }
                }

                var model = new CargoModel
                {
                    Cargos = Cargos
                };

                var response3 = await client.GetAsync(_routes.rota_departamento);

                var result3 = await response3.Content.ReadAsStringAsync();
                var Departamentos = JsonConvert.DeserializeObject<List<Departamento>>(result3);

                ViewData["Title"] = "Cadastro de Cargo";

                ViewBag.Username = User.Identity.Name;
                ViewBag.Departamentos = Departamentos;
                return View("/Views/Cadastro/Cargo/Cargo.cshtml", model);
            }
            return View("/Views/Cadastro/Cargo/Cargo.cshtml");
        }


        [HttpGet]
        [Route("api/Cargo/Cargo/Pesquisar/{id?}/{descricao?}")]
        public async Task<IActionResult> Pesquisar(int id = 0, string descricao = "")
        {
            if (User.Identity.IsAuthenticated)
            {
                var rota = _routes.rota_cargo + id.ToString();

                if (descricao != "")
                    rota += "/" + descricao;

                var response = await client.GetAsync(rota);

                var result = await response.Content.ReadAsStringAsync();
                var response2 = JsonConvert.DeserializeObject<ApiResponseLista>(result);


                if (response2.Sucesso == false)
                {
                    ViewBag.ErrorMessage = "Cargo não encontrado ou ID inválido.";
                    return View("/Views/Cadastro/Cargo/Cargo.cshtml", new CargoModel { Cargos = new List<Cargo>() });
                }

                var model = new CargoModel
                {
                    Cargos = response2.Cargos
                };

                var response3 = await client.GetAsync(_routes.rota_departamento);

                var result3 = await response3.Content.ReadAsStringAsync();
                var Departamentos = JsonConvert.DeserializeObject<List<Departamento>>(result3);

                ViewData["Title"] = "Cadastro de Cargo";

                ViewBag.Username = User.Identity.Name;
                ViewBag.Departamentos = Departamentos;
                return View("/Views/Cadastro/Cargo/Cargo.cshtml", model);
            }
            return View("/Views/Cadastro/Cargo/Cargo.cshtml");
        }



        [HttpPost]
        [Route("api/Cargo/Cargo/Create")]
        public async Task<IActionResult> Create([FromBody] Cargo model)
        {
            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await client.PostAsync(_routes.rota_cargo, content);
            var result = await response.Content.ReadAsStringAsync();
            var apiResponse = JsonConvert.DeserializeObject<ApiResponse>(result);

            if (apiResponse.Sucesso)
            {
                var response2 = await client.GetAsync(_routes.rota_cargo);

                var result2 = await response2.Content.ReadAsStringAsync();
                var Cargos = JsonConvert.DeserializeObject<List<Cargo>>(result2);

                var model2 = new CargoModel
                {
                    Cargos = Cargos
                };

                var response3 = await client.GetAsync(_routes.rota_departamento);

                var result3 = await response3.Content.ReadAsStringAsync();
                var Departamentos = JsonConvert.DeserializeObject<List<Departamento>>(result3);

                ViewData["Title"] = "Cadastro de Cargo";

                ViewBag.Username = User.Identity.Name;
                ViewBag.Departamentos = Departamentos;
                return View("/Views/Cadastro/Cargo/Cargo.cshtml", model2);
            }
            else
            {
                ViewBag.ErrorMessage = apiResponse.Mensagem;
                return View("/Views/Cadastro/Cargo/Cargo.cshtml");
            }
        }

        [HttpDelete]
        [Route("api/Cargo/Cargo/Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            var response = await client.DeleteAsync(_routes.rota_cargo + id.ToString());
            var result = await response.Content.ReadAsStringAsync();
            var apiResponse = JsonConvert.DeserializeObject<ApiResponse>(result);

            if (apiResponse.Sucesso)
            {
                var response2 = await client.GetAsync(_routes.rota_cargo);

                var result2 = await response2.Content.ReadAsStringAsync();
                var Cargos = JsonConvert.DeserializeObject<List<Cargo>>(result2);

                var model2 = new CargoModel
                {
                    Cargos = Cargos
                };

                var response3 = await client.GetAsync(_routes.rota_departamento);

                var result3 = await response3.Content.ReadAsStringAsync();
                var Departamentos = JsonConvert.DeserializeObject<List<Departamento>>(result3);

                ViewData["Title"] = "Cadastro de Cargo";

                ViewBag.Username = User.Identity.Name;
                ViewBag.Departamentos = Departamentos;
                return View("/Views/Cadastro/Cargo/Cargo.cshtml", model2);
            }
            else
            {
                ViewBag.ErrorMessage = apiResponse.Mensagem;
                return View("/Views/Cadastro/Cargo/Cargo.cshtml");
            }
        }

        [HttpPut]
        [Route("api/Cargo/Cargo/Update/{id}")]
        public async Task<IActionResult> Update(int id, [FromBody] Cargo model)
        {
            if (model == null || model.Id != id)
            {
                return BadRequest("Dados do cargo inválidos.");
            }

            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await client.PutAsync(_routes.rota_cargoAlt + id.ToString(), content);
            var result = await response.Content.ReadAsStringAsync();
            var apiResponse = JsonConvert.DeserializeObject<ApiResponse>(result);

            if (apiResponse.Sucesso)
            {
                var response2 = await client.GetAsync(_routes.rota_cargo);

                var result2 = await response2.Content.ReadAsStringAsync();
                var Cargos = JsonConvert.DeserializeObject<List<Cargo>>(result2);

                var model2 = new CargoModel
                {
                    Cargos = Cargos
                };

                var response3 = await client.GetAsync(_routes.rota_departamento);

                var result3 = await response3.Content.ReadAsStringAsync();
                var Departamentos = JsonConvert.DeserializeObject<List<Departamento>>(result3);

                ViewData["Title"] = "Cadastro de Cargo";

                ViewBag.Username = User.Identity.Name;
                ViewBag.Departamentos = Departamentos;
                return View("/Views/Cadastro/Cargo/Cargo.cshtml", model2);
            }
            else
            {
                ViewBag.ErrorMessage = apiResponse.Mensagem;
                return View("/Views/Cadastro/Cargo/Cargo.cshtml");
            }
        }


        public class ApiResponse
        {
            public Cargo Cargo { get; set; }
            public string Mensagem { get; set; }
            public bool Sucesso { get; set; }
        }

        public class ApiResponseLista
        {
            public List<Cargo> Cargos { get; set; }
            public string Mensagem { get; set; }
            public bool Sucesso { get; set; }
        }

        public class ApiResponseListaDepto
        {
            public List<Departamento> Departamentos { get; set; }
            public string Mensagem { get; set; }
            public bool Sucesso { get; set; }
        }
    }
}

Client/Ponto/Controllers/EmpresaController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Ponto.Models;
using Ponto.Views.Cadastro.Departamento;
using Ponto.Views.Cadastro.Empresa;
using System.Text;

namespace Ponto.Controllers
{
    public class EmpresaController : Controller
    {
        private static readonly HttpClient client = new HttpClient();

        private readonly Routes _routes;
        public EmpresaController(Routes routes)
        {
            _routes = routes;
        }

        [HttpGet]
        [Route("api/Empresa/Empresa/Empresa")]
        public async Task<IActionResult> Empresa(string username)
        {
            if (User.Identity.IsAuthenticated)
            {
                var response = await client.GetAsync(_routes.rota_empresa);

                var result = await response.Content.ReadAsStringAsync();
                var Empresas = JsonConvert.DeserializeObject<List<Empresa>>(result);

                var model = new EmpresaModel
                {
                    Empresas = Empresas
                };

                ViewData["Title"] = "Cadastro de Empresa";

                ViewBag.Username = User.Identity.Name;
                return View("/Views/Cadastro/Empresa/Empresa.cshtml", model);
            }
            return View("/Views/Cadastro/Empresa/Empresa.cshtml");
        }


        [HttpGet]
        [Route("api/Empresa/Empresa/Pesquisar/{id?}/{razao?}")]
        public async Task<IActionResult> Pesquisar(int id = 0, string razao = "")
        {
            if (User.Identity.IsAuthenticated)
            {
                var rota = _routes.rota_empresa + id.ToString();

                if (razao != "")
                    rota += "/" + razao;

                var response = await client.GetAsync(rota);

                var result = await response.Content.ReadAsStringAsync();
                var response2 = JsonConvert.DeserializeObject<ApiResponseLista>(result);


                if (response2.Sucesso == false)
                {
                    ViewBag.ErrorMessage = "Empresa não encontrada ou ID inválido.";
                    return View("/Views/Cadastro/Empresa/Empresa.cshtml", new EmpresaModel { Empresas = new List<Empresa>() });
                }

                var model = new EmpresaModel
                {
                    Empresas = response2.Empresas
                };

                ViewData["Title"] = "Cadastro de Empresa";

                ViewBag.Username = User.Identity.Name;
                return View("/Views/Cadastro/Empresa/Empresa.cshtml", model);
            }
            return View("/Views/Cadastro/Empresa/Empresa.cshtml");
        }

        [HttpPost]
        [Route("api/Empresa/Empresa/Create")]
        public async Task<IActionResult> Create([FromBody] Empresa model)
        {
            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await client.PostAsync(_routes.rota_empresa, content);
            var result = await response.Content.ReadAsStringAsync();
            var apiResponse = JsonConvert.DeserializeObject<ApiResponse>(result);

            if (apiResponse.Sucesso)
            {
                var response2 = await client.GetAsync(_routes.rota_empresa);

                var result2 = await response2.Content.ReadAsStringAsync();
                var Empresas = JsonConvert.DeserializeObject<List<Empresa>>(result2);

                var model2 = new EmpresaModel
                {
                    Empresas = Empresas
                };

                ViewData["Title"] = "Cadastro de Empresa";
                ViewBag.Username = User.Identity.Name;
                return View("/Views/Cadastro/Empresa/Empresa.cshtml", model2);
            }
            else
            {
                ViewBag.ErrorMessage = apiResponse.Mensagem;
                return View("/Views/Cadastro/Empresa/Empresa.cshtml");
            }
        }

        [HttpDelete]
        [Route("api/Empresa/Empresa/Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            var response = await client.DeleteAsync(_routes.rota_empresa + id.ToString());
            var result = await response.Content.ReadAsStringAsync();
            var apiResponse = JsonConvert.DeserializeObject<ApiResponse>(result);

            if (apiResponse.Sucesso)
            {
                var response2 = await client.GetAsync(_routes.rota_empresa);

                var result2 = await response2.Content.ReadAsStringAsync();
                var Empresas = JsonConvert.DeserializeObject<List<Empresa>>(result2);

                var model2 = new EmpresaModel
                {
                    Empresas = Empresas
                };

                ViewData["Title"] = "Cadastro de Empresa";
                ViewBag.Username = User.Identity.Name;
                return View("/Views/Cadastro/Empresa/Empresa.cshtml", model2);
            }
            else
            {
                ViewBag.ErrorMessage = apiResponse.Mensagem;
                return View("/Views/Cadastro/Empresa/Empresa.cshtml");
            }
        }

        [HttpPut]
        [Route("api/Empresa/Empresa/Update/{id}")]
        public async Task<IActionResult> Update(int id, [FromBody] Empresa model)
        {
            if (model == null || model.Id != id)
            {
                return BadRequest("Dados da empresa inválidos.");
            }

            var json = JsonConvert.SerializeObject(model);
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var response = await client.PutAsync(_routes.rota_empresaAlt + id.ToString(), content);
            var result = await response.Content.ReadAsStringAsync();
            var apiResponse = JsonConvert.DeserializeObject<ApiResponse>(result);

            if (apiResponse.Sucesso)
            {
                var response2 = await client.GetAsync(_routes.rota_empresa);

                var result2 = await response2.Content.ReadAsStringAsync();
                var Empresas = JsonConvert.DeserializeObject<List<Empresa>>(result2);

                var model2 = new EmpresaModel
                {
                    Empresas = Empresas
                };

                ViewData["Title"] = "Cadastro de Empresa";
                ViewBag.Username = User.Identity.Name;
                return View("/Views/Cadastro/Empresa/Empresa.cshtml", model2);
            }
            else
            {
                ViewBag.ErrorMessage = apiResponse.Mensagem;
                return View("/Views/Cadastro/Empresa/Empresa.cshtml");
            }
        }

        public class ApiResponse
        {
            public Empresa Empresa { get; set; }
            public string Mensagem { get; set; }
            public bool Sucesso { get; set; }
        }

        public class ApiResponseLista
        {
            public List<Empresa> Empresas { get; set; }
            public string Mensagem { get; set; }
            public bool Sucesso { get; set; }
        }
    }
}

Client/Ponto/Views/Shared/_Layout.cshtml
@{
    var currentAction = ViewContext.RouteData.Values["action"]?.ToString();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ponto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ponto.styles.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.4.0/jspdf.umd.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.34/moment-timezone-with-data.min.js"></script>
</head>
<body>
    <header>

    @if (currentAction == "Login")
    {
        @* <div class="container" style="height: 100%;
                margin: 0;
                display: grid;
                place-items: center;">
                <div class="container-fluid" style="height:100%; margin:0; justify-content: center; place-items: center; align-items:center; background-color:aquamarine">
                        <h1 class="display-4" style="margin:2%;font-size:150%; text-align:center">MCP - Meu Cartão de Ponto Eletrônico</h1>
                </div>
        </div> *@
    }

    @if (currentAction != "Login")
    {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Ponto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        @if (ViewBag.Username != "Administrador")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Folha" asp-action="Folha">Folha</a>
                            </li>
                        }
                        @if (ViewBag.Username == "Administrador")
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Cadastro
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Empresa" asp-action="Empresa">Empresa</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Departamento" asp-action="Departamento">Departamento</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Cargo" asp-action="Cargo">Cargo</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="UsuarioFuncionario" asp-action="UsuarioFuncionario">Usuário/Funcionário</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Solicitação
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Solicitacao" asp-action="SolicitacaoAjuste">Solicitação de Ajuste</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Solicitacao" asp-action="FolhaAjuste">Ajuste de Folha de Ponto</a></li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Sair</a>
                        </li>
                    </ul>
                </div>
            </div>           
        </nav>
    }
    </header>
    <div class="container">
        @if (ViewBag.Username != null)
        {
            <div style="background-color:lavender; border-radius:5px; height:80%">
                <h2 style="margin-left: 2%; font-size:100%; color:black">Usuário: @ViewBag.Username</h2>
            </div>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @* <div class="container">
            &copy; 2025 - Ponto
        </div> *@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>